table USUARIO_MATERIA
	lineageTag: 21de2cb0-0411-44d0-98c2-1ee1c59229b4

	column id_usuario_materia
		dataType: int64
		formatString: 0
		lineageTag: 7c0e1077-0abb-4e9e-b29a-f4fb41d09ac2
		summarizeBy: sum
		sourceColumn: id_usuario_materia

		annotation SummarizationSetBy = Automatic

	column id_usuario
		dataType: int64
		formatString: 0
		lineageTag: c91bff0d-eca1-4ad5-95d5-f326dff38d5c
		summarizeBy: none
		sourceColumn: id_usuario

		annotation SummarizationSetBy = Automatic

	column id_materia
		dataType: int64
		formatString: 0
		lineageTag: 0227fa92-5c61-4d34-9e47-986347893d2e
		summarizeBy: sum
		sourceColumn: id_materia

		annotation SummarizationSetBy = Automatic

	column horas_semanales
		dataType: int64
		formatString: 0
		lineageTag: bfe78696-2ead-4046-89ad-6d1217d6adf4
		summarizeBy: sum
		sourceColumn: horas_semanales

		annotation SummarizationSetBy = Automatic

	column cargo
		dataType: string
		lineageTag: 18b9e531-036c-4a22-97fd-0b5e8ea38e70
		summarizeBy: none
		sourceColumn: cargo

		annotation SummarizationSetBy = Automatic

	column dedicacion
		dataType: string
		lineageTag: b0389c2d-0423-4d15-8420-d1436b8c4157
		summarizeBy: none
		sourceColumn: dedicacion

		annotation SummarizationSetBy = Automatic

	partition USUARIO_MATERIA = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\ACER\OneDrive - UTN FRLP\Escritorio\Base de datos GIUCT 5.0.xlsx"), null, true),
				    USUARIO_MATERIA_Table = Origen{[Item="USUARIO_MATERIA",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(USUARIO_MATERIA_Table,{{"id_usuario_materia", Int64.Type}, {"id_usuario", Int64.Type}, {"id_materia", Int64.Type}, {"horas_semanales", Int64.Type}, {"cargo", type text}, {"dedicacion", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

